### ISSUE TITLE
ksqlDB jobs execution Consecutively

### ISSUE THREAD

**Issue by AngeloParrinello** [AngeloParrinello/streaming-materialized-views-benchmarking#1]
#### Description
Currently, if you run the script to automatically reproduce the ksqlDB benchmark locally all the queries will be run in a parallel way, creating a race for the resources between the jobs. It is important to find a way to run a query only when the previous one has finished.

#### Files
In `src/main/resources/bin/ksql/` you will find the script `run-nexmark-local.sh`. Whereas, in `src/main/resources/queries/ksql` are located the queries to execute.

#### To Reproduce
If you follow the `README.md` file and you launch the ksqlDB script for testing ksqlDB locally, you will see (from the command line) that all the queries are executed simultaneously. 

#### Tasks
- [ ] Looking for a mechanism to define the termination of a query in ksqlDB
- [ ] Implement it into the script
- [ ] Test and evaluate the script
